version: '3'

services:

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-stack-redis-commander
    hostname: redis-commander
    restart: always
    ports:
      - "9081:8081"
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - REDIS_HOSTS=master:redis-stack-master:6379:0:kyUQ9xf7knPbYCQt,slave1:redis-stack-slave-1:6379:0:kyUQ9xf7knPbYCQt,slave2:redis-stack-slave-2:6379:0:kyUQ9xf7knPbYCQt
    depends_on:
      - master
      - slave1
      - slave2
      - sentinel1
      - sentinel2
      - sentinel3
    networks:
      - redis-stack

  master:
    image: redis:6
    container_name: redis-stack-master
    hostname: redis-stack-master
    restart: always
    command: redis-server --requirepass kyUQ9xf7knPbYCQt --appendonly yes
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - ${HOME}/docker/redis/master:/data
    networks:
      - redis-stack

  slave1:
    image: redis:6
    container_name: redis-stack-slave-1
    hostname: redis-stack-slave-1
    restart: always
    command: redis-server --replicaof redis-stack-master 6379 --requirepass kyUQ9xf7knPbYCQt --masterauth kyUQ9xf7knPbYCQt --appendonly yes
    ports:
      - "6381:6379"
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - ${HOME}/docker/redis/slave1:/data
    depends_on:
      - master
    networks:
      - redis-stack

  slave2:
    image: redis:6
    container_name: redis-stack-slave-2
    hostname: redis-stack-slave-2
    restart: always
    command: redis-server --replicaof redis-stack-master 6379 --requirepass kyUQ9xf7knPbYCQt --masterauth kyUQ9xf7knPbYCQt --appendonly yes
    ports:
      - "6382:6379"
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - ${HOME}/docker/redis/slave2:/data
    depends_on:
      - master
    networks:
      - redis-stack

  sentinel1:
    image: redis:6
    container_name: redis-stack-sentinel-1
    hostname: redis-stack-sentinel-1
    restart: always
    command: ["redis-sentinel", "/usr/local/etc/redis/redis-sentinel.conf"]
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - ${HOME}/docker/redis/redis-sentinel-1.conf:/usr/local/etc/redis/redis-sentinel.conf
    depends_on:
      - master
    networks:
      - redis-stack

  sentinel2:
    image: redis:6
    container_name: redis-stack-sentinel-2
    hostname: redis-stack-sentinel-2
    restart: always
    command: ["redis-sentinel", "/usr/local/etc/redis/redis-sentinel.conf"]
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - ${HOME}/docker/redis/redis-sentinel-2.conf:/usr/local/etc/redis/redis-sentinel.conf
    depends_on:
      - slave1
    networks:
      - redis-stack

  sentinel3:
    image: redis:6
    container_name: redis-stack-sentinel-3
    hostname: redis-stack-sentinel-3
    restart: always
    command: ["redis-sentinel", "/usr/local/etc/redis/redis-sentinel.conf"]
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - ${HOME}/docker/redis/redis-sentinel-3.conf:/usr/local/etc/redis/redis-sentinel.conf
    depends_on:
      - slave2
    networks:
      - redis-stack

networks:
  redis-stack:
    driver: bridge
