version: "3"

networks:
  gitea:
    external: false

services:

  server:
    image: gitea/gitea:latest
    container_name: gitea
    hostname: gitea
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      -  ${HOME}/docker/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    networks:
      - gitea
