version: '3'

services:

  phpmyadmin:
    container_name: mysql-stack-phpmyadmin
    image: phpmyadmin/phpmyadmin:5.1.1
    hostname: phpmyadmin
    restart: always
    ports:
      - "9080:80"
    environment:
      - PMA_HOSTS=mysql-main,mysql-replica
      - PMA_PORT=3306
    links:
      - mysql-main
      - mysql-replica
    depends_on:
      - mysql-main
      - mysql-replica
    networks:
      - mysql-stack

  mysql-main:
    container_name: mysql-stack-main
    image: mysql:8
    hostname: mysql-main
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ${HOME}/docker/mysql/main:/var/lib/mysql
      - ${HOME}/docker/mysql/conf/main:/etc/mysql/conf.d:ro
    environment:
      - MYSQL_ROOT_PASSWORD=wZ6try8MCNGi6n8P
    networks:
      - mysql-stack

  mysql-replica:
    container_name: mysql-stack-replica
    image: mysql:8
    hostname: mysql-replica
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - ${HOME}/docker/mysql/replica:/var/lib/mysql
      - ${HOME}/docker/mysql/conf/replica:/etc/mysql/conf.d:ro
    environment:
      - MYSQL_ROOT_PASSWORD=wZ6try8MCNGi6n8P
    networks:
      - mysql-stack

networks:
  mysql-stack:
    driver: bridge
